version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: meubanco
      POSTGRES_USER: meuusuario
      POSTGRES_PASSWORD: minhasenha
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: webscraping_app
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://meuusuario:minhasenha@db:5432/meubanco"

volumes:
  pgdata:
